name: Rust
permissions:
  contents: read

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build tests
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build benchmark
      run: cargo build --profile bench --verbose
    - name: Build with defmt
      run: cargo build --features defmt
